#!/bin/bash

# You should only need to run this once.
# However, you can run multiple times,
# it should not change anything after the first run.

add_link() {
  # remove file
  mv -i "$HOME/$1" "$HOME/$1.backup"
  # add soft link
  ln -s "$PWD/$1" "$HOME/$1"
}

add_link '.vimrc'
add_link '.zshrc'
add_link '.tmux.conf'
