alias m='meteor'
alias mrt='meteor'
alias mg='meteor-generator'
alias ms='meteor run --settings settings-development.json'
alias msh='heroku config:add METEOR_SETTINGS="$(cat settings-production.json)"'
alias mshp='heroku config:add METEOR_SETTINGS="$(cat settings-production.json)"'
alias mshs='heroku config:add METEOR_SETTINGS="$(cat settings-staging.json)"'
alias mshd='heroku config:add METEOR_SETTINGS="$(cat settings-development.json)"'
