alias m='meteor'
alias mrt='meteor'
alias mg='meteor-generator'
alias ms='meteor run --settings settings-development.json'
alias mh='heroku config:add METEOR_SETTINGS="$(cat settings-production.json)"'
alias mhp='heroku config:add METEOR_SETTINGS="$(cat settings-production.json)"'
alias mhs='heroku config:add METEOR_SETTINGS="$(cat settings-staging.json)"'
alias mhd='heroku config:add METEOR_SETTINGS="$(cat settings-development.json)"'
